version: '3.1'
services:

  db:
    image: postgres:latest
    container_name: postgres-jkp
    hostname: postgres-jkp
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      PGTZ: Sao_Paulo/Brazil
      TZ: Sao_Paulo/Brazil
    ports:
    - 5433:5432
    volumes:
    - postgres-jkp-volume:/var/lib/postgresql/data
    networks:
    - default
volumes:
  postgres-jkp-volume:
    name: postgres-jkp-volume
    driver: local
networks:
  default:
    name: jkp-networks
    driver: bridge
